### ISSUE TITLE
result is passed to the controller even before `toFile` is finished

### ISSUE THREAD

**Issue by stypr** [ranjandsingh/sharp-multer#6]
https://github.com/ranjandsingh/sharp-multer/blob/0d341c486abe021be5bc243419b5e7fdddfb91cb/index.js#L95-L107

I think this needs to be changed to the following code:

```js
  await stream
    .toFile(path + "/" + filename, function (err) {
      if (err) console.log(err);
      cb(null, {
        filename: filename,
        path: path + "/" + filename,
      });
    });
    // finally
    file.stream.pipe(stream);
```

The problem I am facing is that `cb();` is already called even before the `toFile` operation is complete. 

Precisely, `on("finish", ...)` is already called even before the `.toFile` is complete.

I think the original code doesn't have a problem if the internet is not fast enough. 

However, if the frontend shows the images right after the backend returns the image's URL, the image may get truncated since `.toFile` is still in progress. I think the `toFile` operation needs to be synced before it passes into the controller.

Could you check on this and make appropriate fixes? Thanks in advance!

**Comment by ranjandsingh** [comment]
Hey @stypr thanks for the pointing it out do you mind opening a PR for the same because the change you suggest looks good.
