### ISSUE TITLE
No way to rename the file?

### ISSUE THREAD

**Issue by vincentwinkel** [ranjandsingh/sharp-multer#9]
There is no way to rename the file.
```js
const storageSharp = SharpMulter({
  destination:(req: NextApiRequest, file: any, cb: any) => cb(null, './public/uploads/test'), // Doesn't work (normal, needs to be the folder)
  filename: (req: NextApiRequest, file: any, cb: any) => cb(null, 'test'), // Doesn't work
  filename: 'test', // Doesn't work
  imageOptions: { ... }
});
```

**Comment by ranjandsingh** [comment]
yeah destination needs to be a preexisting folder but I'm not sure why filename  now working |I'll check and get back to you

**Comment by vincentwinkel** [comment]
I guess you should add something like that:
```js
this.getFilename = options.filename || getFilename;
```
instead of directly calling `getFilename`.

**Comment by ranjandsingh** [comment]
@vincentwinkel  adding it now will be available shortly

**Comment by ranjandsingh** [comment]
@vincentwinkel  Hey New Version is live have a look mate and thanks for the issues now it also accepts a function called filename where you can modify the name and return a new name as string cheers

**Comment by vincentwinkel** [comment]
Thank you.
Unfortunately I had to switch to another module since then 😅

**Comment by ranjandsingh** [comment]
no big deal it's fixed for all thanks though.
